[metadata]
name = salesforce_autotest
version = 1.0.0
description = Salesforce UI Recorder and YAML Test Runner
author = Innovation Software Factory
license = MIT
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
include_package_data = True
install_requires =
    selenium>=4.17.0
    pyyaml>=6.0
python_requires = >=3.10

[options.package_data]
* = *.yaml

[options.entry_points]
console_scripts =
    sf-recorder = salesforce_autotest.recorder.gui:main
    sf-run = salesforce_autotest.runner.test_runner:cli_main